### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by ZiGaMi** [GeneralEmbeddedCLibraries/thermistor#1]
- [x] Create configuration to support given HW
 - [x] Configuration validy check
 - [x] Conversion from NTC voltage to temperature calculation
 - [x] Conversion from PT1000 voltage to temperature calculations
 - [x] Temperature sensor status detection
 - [x] Convertion to degF and Kelvins
 - [x] Extensive measurement (all possible HW configurations...)

**Comment by ZiGaMi** [comment]
For NTC calculations use following equation:
![image](https://user-images.githubusercontent.com/33954294/173322427-d466a750-b2c5-47f7-b54d-ad8cd6029c12.png)

**Comment by ZiGaMi** [comment]
```C
////////////////////////////////////////////////////////////////////////////////
/*!
* @brief        Convert NTC voltage to degree C
*
* 			NOTE: 	This function is constrained to HW design. In this scenario
* 					NTC is simply connected to pull-up resistor.
*
* @param[in]    ntc_v 			- Voltage drop across NTC resistor
* @param[in]    beta 			- Beta factor of NTC
* @param[in]    ntc_nominal_val - Nominal value of NTC, typ. @25 degC
* @param[in]    pullup_val 		- Value of pull-up resistor
* @return       temp 			- Calculated temperature
*/
////////////////////////////////////////////////////////////////////////////////
static float32 temperature_NTC_vol_convert_to_degC(const float32 ntc_v, const float32 beta, const float32 ntc_nominal_val, const float32 pullup_val)
{
	float32 temp;
	float32 ntc_r;

	// Catch division by 0
	// This also indicates that something is wrong with temperature sensor
	if 	(	( ADC_EXT_REF_V == ntc_v )
		||	( 0.0f == ntc_nominal_val ))
	{
		ntc_r = 0;

		// Set temperature to error value
		temp = TEMPERATURE_ERROR_VALUE_DEG_CELSIUS;
	}

	// Input valid
	else
	{
		// Calculate NTC resistance
		ntc_r = (float32) (( pullup_val * ntc_v ) / ( ADC_EXT_REF_V - ntc_v));

		// Calculate temperature
		temp = (float32) (( 1.0f / (( 1.0f / 298.15f ) + (( 1.0f / beta ) * log( ntc_r / ntc_nominal_val )))) - 273.15f );
	}

	return temp;
}
```

**Comment by ZiGaMi** [comment]
Solved
